runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
beta_settings:
  'source_reference': 'https://gitlab.univ-nantes.fr/E193433D/tinygram.git#467bd87686283b3663db9df4e7d58ffae2c68fb0'
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'tinygram44.appspot.com'
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.js)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.html)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /NewPost
  script: unused
  login: optional
  secure: optional
- url: /timeline
  script: unused
  login: optional
  secure: optional
- url: /AllPosts
  script: unused
  login: optional
  secure: optional
- url: /NewUser
  script: unused
  login: optional
  secure: optional
- url: /AllUsers
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
